const ANIMATION_FPS = 30
const ANIMATION_FRAME_TIME = 1000 / ANIMATION_FPS
const ANIMATION_FRAME_TIME_SECONDS = ANIMATION_FRAME_TIME / 1000
const MP4_ANIMATION_FPS = 30
const ANIMATION_SECONDS = 5.5
const GIF_ANIMATION_FRAME_TIME_DELAY = ANIMATION_FRAME_TIME_SECONDS * 3
const ANIMATION_SPEEDUP = 1

exports.ANIMATION_FPS = ANIMATION_FPS
exports.ANIMATION_FRAME_TIME = ANIMATION_FRAME_TIME
exports.ANIMATION_FRAME_TIME_SECONDS = ANIMATION_FRAME_TIME_SECONDS
exports.ANIMATION_SECONDS = ANIMATION_SECONDS
exports.ANIMATION_SPEEDUP= ANIMATION_SPEEDUP
exports.GIF_ANIMATION_FRAME_TIME_DELAY = GIF_ANIMATION_FRAME_TIME_DELAY
exports.MP4_ANIMATION_FPS = MP4_ANIMATION_FPS 
